module.exports = [
  {
    makerName : "GNC",
    itemName : "vitamins and supplements",
    link : "https://www.gnc.com/buy-one-get-one-half-off/vitamins-supplements-bogo/?utm_source=cj&utm_medium=affiliate&utm_campaign=afl_cj_b-evgn_pf-none_pb-none_pdc-none_lowf_cx-none_p-none_t-none_g-usnat_d-alla_aflp-4137499&utm_term=13782922_4137499_7278242&utm_content=aff-none&cjevent=daa8ea7db7da11e9801400430a240611",
    discountAmount : "BOGO 50%",
    expirationDate : "8/31/19",
    storeCoupon : true,
    tags : "health",
  },
  {
    makerName : "Walmart",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pizza",
  },
  {
    makerName : "Clorox",
    itemName : "bleach",
    link : "none",
    discountAmount : "$5.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "household",
  },
  {
    makerName : "Giordanos",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00 on TWO",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pizza",
  },
  {
    makerName : "Pantene",
    itemName : "shampoo",
    link : "none",
    discountAmount : "$6.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "bath",
  },
  {
    makerName : "Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pizza",
  },
  {
    makerName : "McDonalds",
    itemName : "burger",
    link : "none",
    discountAmount : "BOGO",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "fast-food",
  },
  {
    makerName : "Little Cesars",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00 on Lunch Box",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pizza",
  },
  {
    makerName : "Rite Aid",
    itemName : "pizza",
    link : "none",
    discountAmount : "$5.00 back when you spend $25",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pharmacy",
  },
  {
    makerName : "Sarah Lee",
    itemName : "pound cake",
    link : "none",
    discountAmount : "Free",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "free",
  },
  {
    makerName : "Talenti",
    itemName : "ice cream",
    link : "none",
    discountAmount : "$1.00 on any two",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "sweets",
  },
  {
    makerName : "MB USA",
    itemName : "SLK550",
    link : "none",
    discountAmount : "$1000 off cash back",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "cars",
  }
]
